- name: Block for get clickhouse distrib
  block:
    - name: Get clickhouse distrib
      ansible.builtin.get_url:
        url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ deploy_clickhouse_clickhouse_version }}.noarch.rpm"
        dest: "./{{ item }}-{{ deploy_clickhouse_clickhouse_version }}.rpm"
        mode: '0655'
      with_items: "{{ deploy_clickhouse_clickhouse_packages }}"
  rescue:
    - name: Get clickhouse distrib
      ansible.builtin.get_url:
        url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{ deploy_clickhouse_clickhouse_version }}.x86_64.rpm"
        dest: "./clickhouse-common-static-{{ deploy_clickhouse_clickhouse_version }}.rpm"
        mode: '0655'

- name: Install clickhouse packages
  become: true
  ansible.builtin.yum:
    name:
      - clickhouse-common-static-{{ deploy_clickhouse_clickhouse_version }}.rpm
      - clickhouse-client-{{ deploy_clickhouse_clickhouse_version }}.rpm
      - clickhouse-server-{{ deploy_clickhouse_clickhouse_version }}.rpm
  notify: Start clickhouse service

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Block for checking service clickhouse status
  block:
    - name: Checking service clickhouse status
      ansible.builtin.command: systemctl status "{{ item }}"
      with_items:
        - clickhouse-server
      register: clickhouse_server_status
      changed_when: true
  rescue:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted

- name: Verify clickhouse-server is listening on 9000
  ansible.builtin.wait_for:
    port: 9000
    timeout: 5

- name: Create database
  ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
  register: create_db
  failed_when: create_db.rc != 0 and create_db.rc != 82
  changed_when: create_db.rc == 0
