---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - role: 'deploy_clickhouse'
      tags:
        - clickhouse

- name: Install Vector
  hosts: vector
  roles:
    - role: 'deploy_vector'
      tags:
        - vector
