---
- name: Install Clickhouse
  hosts: clickhouse
  vars:
    ansible_user: centos
  roles:
    - role: 'deploy_clickhouse'
      tags:
        - clickhouse

- name: Install Vector
  hosts: vector
  vars:
    ansible_user: centos
  roles:
    - role: 'deploy_vector'
      tags:
        - vector

- name: Install LightHouse
  hosts: lighthouse
  vars:
    ansible_user: centos
  roles:
    - role: 'deploy_lighthouse'
      tags:
        - lighthouse
